language: scala
scala:
- 2.11.6
jdk:
- oraclejdk7
# - openjdk7

TRAVIS_USERNAME:
  secure: f7aprTSWC0BAbzZV+xlXiWu8zwQQePaIVp1KGIOgk0feMbvUK+Ce6ETgW62WyjjbwF9OYNr3iiffHZj9MkS4zrguCVgdgPER+m9TRhZGA0IGYwTyPPmeYr5P3B1DDAwnnSQwIfJvBhLOB3V/z1dzZk5NUzE+csI51hVdZHO/rCI=
TRAVIS_PASSWORD:
  secure: qABMEbXNnfFBkngkFtXG+nVeu+zQqSZcys+ZPs2sFYgeRmWBoKoy1vujHS8Ecz8m5rWNTcJ+EzFSvkmE3fRV535MapTUmFUDeOkWjh0gdrnosah487nOizaL2gOIHQHyYGL0DINiSyVzWfKaAI0z0uY3oNucdd0QFSY6r6lsNFU=
