language: scala
scala:
   - 2.11.4
jdk:
- oraclejdk7

branches:
  except:
    - travis

before_install:
- git clone -b travis `git config --get remote.origin.url` target/travis

script:
- mvn deploy artifactory:publish -P core,archetypes,ojo --settings target/travis/settings.xml

after_success:
- mvn site-deploy -P core,archetypes,github-site -Dgithub.global.oauth2Token=$GITHUB_TOKEN
- sbt coverageAggregate
- sbt coveralls

env:
  global:
  - secure: ZlMzvn7Jlxbzbd8MNsxerPVPiTXXYdRj6i+AhyYN69nmjF9Re5Y6xaViEpxqL7jXL/0qQUKtM2he7TJFxzuhxZc32N0OCQ0euCuE6krBygRZ7Re+CFKEjGp1WCnySDpcpqWeDYKAvk6OtWm5q3TW+pFwF0UT/aL7xT0wdJrN8fU=
  - secure: oi5wtujkvD+B6oUEl8xFaW7bv2KilVX+v1mxS9WH5lHH0ei0RdCPbDcUR+9wqEfMzybPfmazvgK2UFk6GfrSuIR33iSJ3+MG9UMApUlX9eSgn7QM2OfZa/sLNjTKCjDnsTpRE+59VPBGEQsRTWVm2fl/iffyRZ/ervtd+qffcy8=
  - secure: UEwEEb3YXIgwofNBaaKBuqiyTNXOAqjfvJ+zPU6lUqJsoqPfemWL4Ikb7K8bA2domIgVAiMKmPm3FCAKFeeqm2QLRt0MQmqW6RUmKWFm2/12w9m3CFvTnBpDDdk8HUleXxs1FFZdflWYecBmoJqq8djO/wz7dJbPuPZkKU1NlLM=
